### ISSUE TITLE
ARM64 and aarch64 support

### ISSUE THREAD

**Issue by sunjam** [CollaboraOnline/richdocumentscode#13]
Hi, great job on this.  I'd like to request a version of this for ARM hardware.  This would allow compatibility with projects like [NextcloudPi](https://github.com/nextcloud/nextcloudpi/), which is an official part of [Nextcloud](nextcloudpi.com) that targets additional architectures such as ARM.

I'm not clear on your system requirements for specific numbers of users, but I know the latest Pi [supports 8gb of ram](https://www.tomshardware.com/news/raspberry-pi-4-8gb-tested) and other recent devices are usually at 2gb - 4gm of ram, plus support ARM 64-bit operating systems.

**Comment by elpraga** [comment]
Indeed! aarch64 support would be great to see!

**Comment by csolisr** [comment]
The same problem was reported with the [Docker version](https://github.com/CollaboraOnline/Docker-CODE/issues/92), the issue being that the precompiled packages from the repository are built exclusively for x86-64. I attempted building an ARM version for my Raspberry Pi 4, using [an unofficial script](https://github.com/husisusi/officeonlin-install.sh), but it failed to download the whole LibreOffice code repository required to build (probably due to the sheer size of the code base?).

**Comment by timar** [comment]
We've got ARM64 support for a while, closing this old issue.

**Comment by elpraga** [comment]
Is there a chance you might provide a PPA for Ubuntu ARM64 the same way you provide it for x86_64?
