### ISSUE TITLE
Can not run worksheets macros due to no access to the loolwsd.xml configuration file

### ISSUE THREAD

**Issue by kitatek** [CollaboraOnline/richdocumentscode#131]
Collabora Online - Built-in CODE Server	6.4.705
Collabora Online	3.7.18
Nextcloud 20.0.5

Hello,

Macros do not run in the built-in CODE.

Collabora announced the availability to run macros in spreadsheets in [this post](https://www.collaboraoffice.com/integration/how-to-use-and-manage-macros-in-collabora-online/).

However this requires to access the loolwsd.xml configuration file.

It seems the built-in CODE does not offer to configure that.

Or am I missing something ?

**Comment by mmeeks** [comment]
Hi Kitatek, so the built-in app-image version of CODE has rather limited security containment due to its lack of OS / capabilities which we need to chroot and lock down each document's process. As such it would be really unhelpful to allow arbitrary macros from other users to run in this configuration even with a prompt. Users are encouraged to upgrade to a more performant and secure docker-image, or to install the native packages and use a real websocket connection =)
Thanks for reporting !
