### ISSUE TITLE
Unable to install (Invalid architecture: x86_64)

### ISSUE THREAD

**Issue by Anaerin** [CollaboraOnline/richdocumentscode#184]
As per https://github.com/nextcloud/richdocuments/issues/2186 I'm filing this one here.

Describe the bug
-------------------
Attempting to install the CODE server, I get the an error saying the architecture is not supported.

To Reproduce
---------------
*Steps to reproduce the behavior:*

Open Nextcloud Apps as admin
Click "Install" on
Expected behavior
The app installs.

`App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64`

Client details:
---------------

OS: Windows 11
Browser: Chrome
Version: 100.0
Device: Desktop

Server details
---------------

Operating system: FreeBSD 12.0/TrueNAS 12 jail
Web server: nginx
Database: MySQL 8.0.26
PHP version: 7.4.25
Nextcloud version: 23.0.4
Version of the richdocuments app: N/A yet
Version of Collabora Online: N/A

**Comment by VileLasagna** [comment]
Bumping this as I'm experiencing the same problem. Tried both through the UI and through occ CLI, same issue.
Server is running on a TrueNAS Jail as well, version 24.0.1. Underlying architecture is definitely x86_64, as it's running on an AMD Ryzen 7 4750G

**Comment by Anaerin** [comment]
Yes. `x86_64` identifies the OS as 64-bit, as opposed to `x86`, `i386` or `i686` which are all 32-bit versions.

**Comment by VileLasagna** [comment]
Specifically, this is what I get on mine:

```
FreeBSD 12.2-RELEASE-p10 b26f74b5984(HEAD) TRUENAS 

	TrueNAS (c) 2009-2021, iXsystems, Inc.
	All rights reserved.
	TrueNAS code is released under the modified BSD license with some
	files copyrighted by (c) iXsystems, Inc.

	For more information, documentation, help or support, go here:
	http://truenas.com
Welcome to TrueNAS

Warning: settings changed through the CLI are not written to
the configuration database and will be reset on reboot.

root@sequencer[~]# uname -m
amd64
```

This IS 64 bit but maybe somewhere it's missing that string on a list of valid 64 bit architectures?

**Comment by lbdroid** [comment]
I have a theory that your issue might be because its comparing "amd64" to "x86_64" on a string equality basis. From a Linux server;

```
$ uname -m
x86_64
```

**Comment by lbdroid** [comment]
Oh, and also your OS is BSD. System requirements call specifically for Linux.

**Comment by VileLasagna** [comment]
String comparison is my guess as well. Couldn't find anything regarding BSD incompatibility, hoping it's not that giving it'll run through the web server that's hosting the nextcloud instance. If it IS that, then it would be good to tweak the description of the nextcloud app.... and then I need to source a workaround of some sort because I kind of need to get this sorted

**Comment by lbdroid** [comment]
It says right in the readme for THIS project, LINUX.

And seeing as this runs a binary backend server that depends on system libraries, I find it very unlikely that the prebuilt would work on a different OS. In fact, it barely even works on Linux unless you're running the exact same distro, version, and configuration as they made it on.

**Comment by VileLasagna** [comment]
Hmmm... going over the readme over here it does indeed say "Linux". It is always fuzzy between Linux and BSD though so without knowing the guts a bit better I wouldn't know if there are any blocking issues there (though, yeah, if there's a big native binary underneath and all that, that's quite likely)

If it is indeed the case that this is not expected to run on a BSD-based system, I think it would be very helpful it the description of the Nextcloud app is updated to reflect this. It's an easy enough PR to do for the xml, just not sure what's consistent language here as I'm new to this side of things. This to me FEELS like it's unexpected because I assumed people had been trying to run this from TrueNAS based servers fairly constantly, as Nextcloud is one of the big featured packaged services there so being caught off guard here felt unusual.

Additionally, should this confirm, I also need to figure out how to do all of this "manually", I guess... as I still DO very much want to run Collabora on my NAS, even if I need to jump through a few extra hoops to get it up

**Comment by VileLasagna** [comment]
Double posting here to clarify.

After digging beyond the docs directly on the Nextcloud side of things, confirmed that @lbdroid was on the money here. 
Still think that the way to go here is to add a disclaimer to the nextcloud app description since the error we end up getting is misleading (it complains about architecture but the true issue is OS flavour)

As for actually getting Collabora up, the general understanding seems to be that the way to go, if you're running everything from a TrueNAS box (which is my case and apparently @Anaerin 's as well) is to fire up a Linux VM and run the CODE server from there (with docker being the easiest way to get that sorted). Then just install the App on Nextcloud (but not the built-in server) get that configured, sort whatever reverse proxying shenanigans you might need for your set-up and go from there. There's a pretty good guide [available on the Nextcloud forums](https://www.truenas.com/community/resources/nextcloud-and-collabora-integration.140/) which should get you most of the way there, though I'd warn that the NGINX config there is outdated as some stuff have moved around.

In the end though, I struggled with this for two days and it would just not work for me and, try as I might, I couldn't find what was wrong. Worked with demo server but just wouldn't talk proper to my own, no matter how much I tried. I ended up doing a similar setup for OnlyOffice instead, so that's a potential alternative. I may end up crying for help on the Nextcloud forums or something later on, to give Collabora a chance as an alternative but for now, just tired although happy I got something sorted in the end.

Thanks for helping to spot that, @lbdroid and good luck on your shenanigans, @Anaerin

**Comment by lbdroid** [comment]
You could also try building collabora online directly for your architecture;
https://collaboraonline.github.io/post/build-code/

**Comment by BHuck74** [comment]
Dear all,

I'm experiencing this issue because running  also Nextcloud on TrueNAS Jail. My solution was to create a Docker container running Collabora Code on an alternate server... A kind of gaz factory but it does work...

Would be great to get a Nextcloud version  that supports BSD environments...

**Comment by VileLasagna** [comment]
Oh, hello there.

I mentioned last time that I may eventually give Collabora a second chance and the time for that has indeed come. Something went wrong with my OO server and I wanted to use the opportunity to recreate my VM for docker services using OpenSUSE MicroOS, so ended up doing the whole back and forth again.

It took me another two or three days of bashing my head against collabora's config, my own NGINX setup, triple checking SSL certs and settings and things still wouldn't work. I could access the CODE server's admin web interface but couldn't open any documents at all, was tearing my hair out.... UNTIL I noticed uBlock Origin was blocking some "ads" on my own Nextcloud server.

> This is the important bit that got things working for me
Turns out uBlock Origin had a couple of rules that filtered out the document request from the Nextcloud side so it never reached the CODE server. Once I added exceptions, things started working and have been pretty great so far. 

This was a real pain to diagnose because since the request got blocked I didn't have any logs or anything from Collabora's side, and since it was dependent on the formation of my server's URL, the demo server would work without any issues.


So yeah, as @BHuck74 also confirmed, the way to go is having a different server or, as is my case, VM, running Linux so you can host the CODE server from. I'm running a MicroOS VM on the same physical server, using the docker image for CODE server through podman and using the NGINX config provided on the docs
