### ISSUE TITLE
Collabora Online - Built-in CODE Server (ARM64) - NC26 compatibility

### ISSUE THREAD

**Issue by elpraga** [CollaboraOnline/richdocumentscode#218]
The **Collabora Online - Built-in CODE Server (ARM64)** is listed as not being compatible with NC26.

Unfortunately, this is one of the apps that I do need daily, so I cannot simply upgrade and then try it works by enabling untested app.

Can someone test the compatibility?

**Comment by juanejot** [comment]
While the pre-installed (to work with, at latest, NC25.0.5) ARM64 CODE Server 22.5.802 _does_ work under Nextcloud 26 Server running on an RPi4B, I had to explicitly go to the Apps page, search out CODE Server (ARM64), and select "Enable untested app," that warning goes away, but I _still_ needed afterward to find it again and select "Enable."

While this "Are you sure?"-style web interface guardrailing is a good idea for new NC servers with which richdocumentscode(_arm64) has yet to be tested, it seems odd that no testing is yet acknowledged when the NC26 beta cycle is well over, and the full version is out.

I can't speak to all potential use cases, but the CODE Server worked on the same LAN* via WiFi or Ethernet, as well as over cellular (so, not the same LAN) provided that the allow list for WOPI requests was accurate. By "work," I mean I could open up, edit & save .odt docs of similar complexity as I always had, via NC and Collabora apps, as well as via the web, on various devices. Speed was first-run slow but not insufferable, anecdotally equivalent to the first-run of the CODE Server running on NC25. I don't know how PHP caching will speed things up over the long term, but I assume that that speed too will be comparable.

*My only issue so far has been with fail2ban blocking the router's IP on the LAN (thus blocking LAN access) within probably 5 minutes of enabling the CODE Server app, but this was also within 5~10 minutes of completing the NC server upgrade, so it's likely due to the volume of all the new hits to _all_ renewed NC services, _not_ just to the CODE server. Easily unbanned, and LAN access was restored. Regardless whether it was due to frenzied first-run NC26 access at large or due to CODE Server access specifically, the ban has yet to recur after >24 hours.

**Comment by timar** [comment]
The new release 22.5.1301 has the Nextcloud 26 compatibility commit in it, so I think this issue can be closed. Sorry for the delay, the versions between 22.5.802 and 22.5.1301 simply did not work due to a heisenbug! So we did not release them.
