### ISSUE TITLE
i can´t use app

### ISSUE THREAD

**Issue by julbroa** [CollaboraOnline/richdocumentscode#36]
I needed to download the application to be able to install it. When I try to activate it I get the following error

App "richdocumentscode" cannot be installed because appinfo file cannot be read

i have shared hosting on hostinger.

**Comment by g-work** [comment]
Propably timeout or too low memory limit. Try to increase both.
Had the same problem via webinterface, installing via occ command worked.

**Comment by syntron** [comment]
I have a similar probelm with the updates for this app; Thus, I'm using the console app; try the following command to update all apps:

`sudo -u wwwrun /usr/bin/php -f /srv/www-extern/apps/nextcloud/occ app:update --all`

change the user (wwwrun) and path (/srv/www-extern/apps/nextcloud/) according to your system settings.

Installing the app should use a similar command:

`sudo -u wwwrun /usr/bin/php -f /srv/www-extern/apps/nextcloud/occ app:install richdocumentscode`

**Comment by bcutter** [comment]
I managed to install using OCC command. Anyway, the CODE server is not showing up as option on https://my-nextcloud-server.org/index.php/settings/admin/richdocuments page...!

**Comment by timar** [comment]
Hoster may restrict php, e.g. users are not allowed to exec binaries from php, etc. In this case the  app won't work.

**Comment by baal2048** [comment]
la solution de Syntron fonctionne chez moi, pour colabora online, suite à un changement de serveur après la réstauration des fichiers CODE ne fonctionnait plus, je suis sous Ubuntu serveur 18.04, j'ai donc utilisé ces commandes : 

sudo -u www-data php -f occ app:update --all

sudo -u www-data php -f occ app:remove richdocumentscode
sudo -u www-data php -f occ app:install richdocumentscode

sudo -u www-data php -f occ app:remove richdocuments
sudo -u www-data php -f occ app:install richdocuments

depuis CODE dans l'interface web et sous android fonctionne de nouveau.


Merci.

**Comment by m-schmoock** [comment]
Theres something broken about the app installer in this case (for a long while).
I frequently run into this issue, and when manually executing the `occ app:install richdocumentscode` command may still run into `App "richdocumentscode" cannot be installed because appinfo file cannot be read`.

When this happens the folder structure of the richdocumentscode app is broken. It seems that the extraction of this package has an recusion issue where it extracts 'richdocumentscode' into a folder already named 'richdocumentscode'. This works, but is wrong and the appinfo xml will end up in the wrong place:  `/custom_apps/richdocumentscode/richdocumentscode/appinfo` 

However its easy to fix:

 - go to your html servers filesystem where it stores the custom apps, e.g. `cd /var/www/html/custom_apps`
 - remove richdocumentscode:   rm -r richdocumentscode
 - go back to you html base folder, e.g.: `cd /var/www/html`
 - install again via occ:  `php occ app:install richdocumentscode`

Some systems may require `sudo -u www-data ... ` as mentioned above.

**Comment by bcutter** [comment]
Maybe fix the app installer instead? Just a total crazy idea.

**Comment by m-schmoock** [comment]
> Maybe fix the app installer instead? Just a total crazy idea.

Yeah I know, just wanted to drop this info here, incase other users stumble across the same issue...

**Comment by dedors** [comment]
**Problem:** After updating to Nextcloud 31, the "richdocumentscode" app couldn't be installed due to "appinfo file cannot be read". Worked fine before the update.

**Environment:** Nextcloud 31 in Docker (no `sudo` in container).

**Cause:** A `.fuse` file in the `richdocumentscode` app folder prevented removal inside the Docker container.

**Workaround:**

1.  Stop Docker.
2.  Delete the `richdocumentscode` folder on the host.
3.  Restart Docker.
4.  Install via `occ app:install richdocumentscode`.
