### ISSUE TITLE
Requests sent over HTTP instead of HTTPS regardless of set URL

### ISSUE THREAD

**Issue by Xerbo** [CollaboraOnline/richdocumentscode#45]
**Bug Description**
Requests gets sent to `http://cloud.DOMAIN.net` instead of `https://cloud.DOMAIN.net`, which doesn't load due to mixed content blocking, even with that disabled it still runs into CORS issues due to differing domains. No matter what the URL is set to it still resorts to http.

**What's Expected To Happen**
Collabera automatically detects that NextCloud is being severed over https (maybe from the `overwriteprotcol` option) and uses a HTTPS link.

**What Actually Happens**
Collabera defaults to HTTP with no way of changing it.
Although `wopi_url` gets set to whatever you enter, `public_wopi_url` does not, and always uses HTTP 

**Software**
NC 19.0.1 behind a nginx reverse proxy with a LetsEncrypt certificate.

**Comment by raffisweb** [comment]
This is the biggest problem with NC so far. I see a lot of comments on this in different tickets. Should be easy to repair... SSL by default!

**Comment by weitangli** [comment]
I use nginx, how to repair?

**Comment by cguess** [comment]
I'm experiencing this same issue with the same set up as @Xerbo, is there any fix for this coming? It's simply the default docker image with a very common reverse-proxy setup.

**Comment by alderson59** [comment]
I'm running into this issue too. NC behind nginx reverse proxy. What do I need to edit to serve the mixed content over https instead of http?

**Comment by alderson59** [comment]
Just figured this out:

/nextcloud/html/custom_apps/richdocumentcode/proxy.php > line 239

```
// URL into this server of the proxy script.
if (isset($_SERVER['HTTPS'])) {
    $proxyURL = "https://";
} else {
    $proxyURL = "http://";
}
```
Set the latter to ` $proxyURL = "https://";`

**Comment by cguess** [comment]
You really don't want to serve mixed content of your documents. That's a huge security hole.

Eventually I just set up a separate standalone Collabora server with NGINX handling the https for that on a separate domain. (Note: if you do this, you have to make sure NGINX also handles `wss://` websocket requests, upgrading them properly. If anyone wants the instructions to do that I'll dig into my configurations, just let me know.)

**Comment by alderson59** [comment]
@cguess 
Sorry, not a professional in this, but I think I understand what you mean - instead of connecting your collabora instance locally (i.e. 127.0.0.1 or 172.17.0.1), you send it out to the internet (collabora.domain.com), and nextcloud attaches to it via the external domain?

But how would this affect performance? It would send traffic over the internet instead of directly, albeit encrypted? 

Is there an easy way to just use the former (local) method AND serve content via https? (I use an nginx proxy, and this has SSL certs managed. My NC instance goes thru this too).

**Comment by cguess** [comment]
@alderson59 Happy to help you out a bit, since I banged my head over this for days.

Your second edit is on track here, but honestly: I couldn't get the local, integrated server, to work. Instead I ended up setting up a separate Collabora instance (using docker compose), using NGINX to reverse proxy that as well, and then making sure that websockets are properly upgraded in the NGINX config for the collabora subdomain. I'm happy to write out a few steps if you need it (because that's a lot), just let me know.

**Comment by alderson59** [comment]
Full disclosure - I'm using jc21/nginx-proxy-manager to reverse proxy the connection. I set it to use https over the 192.168 connection with websockets enabled. In doing so, the "Collabora Online server is reachable" turns green in NC settings. 

I'm also using docker collabora/code. Followed the docker run commands in the manual.

After that, I tried editing a file using Collabora and came up with the error in EDIT2. "collabora.domain.com refused to connect"

I haven't touched the loolwsd.xml config file - are there any settings to change here? I think server_name may be required (since it says it's required when using a reverse proxy), but upon testing it, didn't really solve anything. Also it's a PITA to edit this file per the documentation (docker cp out, and docker cp back in). Tried to do a volume but it messes up permissions for me, since lool is 101:102, which is systemd-resolve on my host. Doing this makes the container keep restarting... But I digress.

Limited experience in nginx, but let's see where this takes us! Would really appreciate your help :)

**Comment by IanChok** [comment]
@cguess What was your `nginx.conf` set up looking like? In Chrome, I'm getting the error:
`Mixed Content: The page at 'https://collabora.domain1.com/apps/files/?dir=/Executives/Finance&fileid=868' was loaded over HTTPS, but requested an insecure form action 'http://collabora.domain1.com/loleaflet/0b3211b/loleaflet.html?WOPISrc=https%3A%2F%2Fcollabora.domain1.com%%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1729_ocixug9hl9fs&title=investments.ods&lang=en&closebutton=1&revisionhistory=1'. This request has been blocked; the content must be served over HTTPS.
`

I have a docker-compose.yml file that looks like this:
```yaml
version: '3.3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./access_log:/var/log/nginx/hts-il-db-lb-access.log
      - ./error_log:/var/log/nginx/hts-il-db-lb-error.log
    ports:
      - 80:80
      - 443:443
  collabora:
    privileged: true
    image: collabora/code
    container_name: collabora
    ports:
      - 9980:9980
    environment:
      - domain=mydomain1.com|mydomain2.com
      - extra_params=--o:ssl.enable=false
    restart: always
networks:
  default:
    external: true
    name: nginx-network
```

And my `nginx.conf` file looks like this:

```
events {}
http {
  server {
    server_name collabora.mydomain1.com;
    
    listen 443 ssl;
    
    ssl_certificate /etc/letsencrypt/live/collabora.mydomain1.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/collabora.mydomain1.com/privkey.pem;
   

    # static files
    location ^~ /loleaflet {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # WOPI discovery URL
    location ^~ /hosting/discovery {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # Capabilities
    location ^~ /hosting/capabilities {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # main websocket
    location ~ ^/lool/(.*)/ws$ {
        proxy_pass http://collabora:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }

    # download, presentation and image upload
    location ~ ^/lool {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        client_max_body_size 50M;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frame-Options SAMEORIGIN;
        proxy_buffers 256 16k;
        proxy_buffer_size 16k;
        client_body_timeout 60;
        send_timeout 300;
        lingering_timeout 5;
        proxy_connect_timeout 90;
        proxy_send_timeout 300;
        proxy_read_timeout 90s; 
   }

    # Admin Console websocket
    location ^~ /lool/adminws {
        proxy_pass http://collabora:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    } 

   error_log /var/log/nginx/hts-il-db-lb-error.log debug;
  }
}
```

**Comment by ftoledo** [comment]
i still have thi issue

**Comment by AlexanderSlaa** [comment]
> Just figured this out:
> 
> /nextcloud/html/custom_apps/richdocumentcode/proxy.php > line 239
> 
> ```
> // URL into this server of the proxy script.
> if (isset($_SERVER['HTTPS'])) {
>     $proxyURL = "https://";
> } else {
>     $proxyURL = "http://";
> }
> ```
> 
> Set the latter to ` $proxyURL = "https://";`

Fixed it for me. i just deleted the if-else statement and replaced it by

```php
 $proxyURL = "https://";
```

**Comment by erahhal** [comment]
Is Nextcloud integration just broken?  I can't find any change that will fix this.  I'm on the latest Nextcloud and can't find the `proxy.php` file mentioned above.  But that's not optimal either as I'm running using a docker container and would prefer not to have to manually modify the code and build a new docker image every time Nextcloud is updated.

**Comment by MohammedNoureldin** [comment]
Did you figure it out, @erahhal?

**Comment by MohammedNoureldin** [comment]
@erahhal did you find any better approach? Still when I enable the ssl param the instance cannot start because it misses the certificates. Anyway, TLS from the Nginx should be actually sufficient.

Please let me know if you found any solutoin.

**Comment by Foxxify1** [comment]
Specifics:
Running Nextcloud AIO, Collabora, and Nginx Proxy Manager (for reverse proxy) in docker containers.
Nextcloud has NC Office installed
SSL certificates are signed using Let's Encrypt
All necessary ports are allowed through the firewall

If I made the proxy scheme http in NPM, going to http://collabora.mydomain.com in the browser would say OK.
If the scheme was https in NPM, going to https://collabora.mydomain.com in the browser would result in a 503 error.
In neither case (http or https) adding the domain to "Use your own server" of NC Office work.

Fix:
> If you are running a docker container and followed the Nextcloud integration instructions online, it tells you to add an environment variable, `extra_params=--o:ss.enable=false`. Don't do this; get rid of that.

Removing this line from the Collabora container fixed my error of Collabora not resolving on an https connection, and subsequently make the Collabora server reachable. (Used Yacht to remove the offending line and redeploy the container)

thanks for this nugget
